### ISSUE TITLE
github install joshbleiberg/stackedev: file c:\ado\plus/g/github.dta could not be opened r(603)

### ISSUE THREAD

**Issue by georgehuangcool** [joshbleiberg/stackedev#1]
I try to run:

`github install joshbleiberg/stackedev`

but get error: file c:\ado\plus/g/github.dta could not be opened

**Comment by joshbleiberg** [comment]
Try:
<sup>ssc install stackedev</sup>

**Comment by georgehuangcool** [comment]
`ssc install stackedev` is fine!
